#!/bin/sh

# common alias
alias ls="ls -F"
alias ll='ls -lhG'  # -l long listing, human readable, no group info
#alias ll="ls -l"
alias la="ll -ah"
alias lt="la -t"
alias lr="lt -r"
alias pw="pwd"

alias ..='cd ..'
alias ...='cd ../..'
alias t='tail -fn'

alias h='history'
alias cdw='cd ~/Workspace'
alias mysql_stop='/usr/local/bin/mysqladmin -u root -p shutdown'
alias mysql_start='/usr/local/bin/mysqld_safe &'

alias pg-start='pg_ctl -D /usr/local/var/postgres/data -l /usr/local/var/postgres/log/server.log start'
alias pg-stop='pg_ctl stop -m fast'
alias pg-status='pg_ctl status'
alias pg-restart='pg_ctl reload'
