#!/bin/sh

# common alias
alias ls="ls -F --color"
alias ll='ls -lhG'  # -l long listing, human readable, no group info
alias la="ls -alh --color"
alias lt="la -t"
alias lr="lt -r"

alias ..='cd ..'
alias ...='cd ../..'
alias t='tail -fn'

alias h='history'
alias cdw='cd /vagrant/'
alias cdg='cd ~/go/'
alias publish='python -m SimpleHTTPServer 5000'

# alias mysql_stop='/usr/local/bin/mysqladmin -u root -p shutdown'
# alias mysql_start='/usr/local/bin/mysqld_safe &'
alias publish='python -m SimpleHTTPServer 5000'

alias pg-start='pg_ctl -D /usr/local/var/postgres/data -l /usr/local/var/postgres/log/server.log start'
alias pg-stop='pg_ctl stop -m fast'
alias pg-status='pg_ctl status'
alias pg-restart='pg_ctl reload'
