#!/bin/sh 

# common alias
alias ls="ls -F"
alias ll='ls -lhG'  # -l long listing, human readable, no group info
#alias ll="ls -l"
alias la="ll -ah"
alias lt="la -t"
alias lr="lt -r"
alias pw="pwd"

alias h='history'
# alias mysql_stop='mysqladmin5 -u iver_root -p shutdown'
# alias mysql_start='sudo mysqld_safe5 &'

alias mysql=/usr/local/mysql/bin/mysql
alias mysqladmin=/usr/local/mysql/bin/mysqladmin
alias ..='cd ..'
alias ...='cd ../..'
alias t='tail -fn'

