#!/bin/sh

# common alias
alias ls="ls -F"
alias ll='ls -lhG'  # -l long listing, human readable, no group info
#alias ll="ls -l"
alias la="ll -ah"
alias lt="la -t"
alias lr="lt -r"
alias pw="pwd"

alias ..='cd ..'
alias ...='cd ../..'
alias t='tail -fn'

alias h='history'
alias cdw='cd ~/Workspace'
# alias mysql_stop='mysqladmin5 -u iver_root -p shutdown'
# alias mysql_start='sudo mysqld_safe5 &'

alias postgres.server='pg_ctl -D /usr/local/var/postgres/data -l /usr/local/var/postgres/server.log'

