#!/bin/sh

# paths
# --
# (c) Iver!
# Iván Jaimes <iver@iver.mx>
#

# Config file to go

# input mode
umask 0007

config () {
  [ -d /usr/local/go ] && export GOROOT=/usr/local/go
  [ -d ${HOME}/Workspace/go ] && export GOPATH=${HOME}/Workspace/go
  [ -d ${GOPATH}/bin ] && export GOBIN=${GOPATH}/bin
  PATH=${PATH}:${GOBIN}
}

config
